#!/usr/bin/env bash

set -euo pipefail

echo "# Generated by scripts/generate-env-local.sh"
echo

pnpm supabase status -o env \
  | grep -E '^(API_URL|PUBLISHABLE_KEY)=' \
  | sed -e 's/^API_URL=/VITE_SUPABASE_URL=/' -e 's/^PUBLISHABLE_KEY=/VITE_SUPABASE_PUBLISHABLE_KEY=/'
