/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as pagesRouteRouteImport } from './routes/(pages)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as pagesuserRouteRouteImport } from './routes/(pages)/(user)/route'
import { Route as pagessearchIndexRouteImport } from './routes/(pages)/(search)/index'
import { Route as ApiAssetAssetIdRouteImport } from './routes/api/asset/$assetId'
import { Route as ApiAlbumsAlbumIdRouteImport } from './routes/api/albums/$albumId'
import { Route as pagesProfileProfileIdRouteImport } from './routes/(pages)/profile.$profileId'
import { Route as pagesAssetsAssetIdRouteImport } from './routes/(pages)/assets/$assetId'
import { Route as pagesAlbumsAlbumIdRouteImport } from './routes/(pages)/albums/$albumId'
import { Route as pagesuserFavoritesRouteImport } from './routes/(pages)/(user)/favorites'
import { Route as authAuthUpdatePasswordRouteImport } from './routes/(auth)/auth/update-password'
import { Route as authAuthForgotPasswordRouteImport } from './routes/(auth)/auth/forgot-password'
import { Route as authAuthConfirmErrorRouteImport } from './routes/(auth)/auth/confirm-error'
import { Route as authAuthConfirmRouteImport } from './routes/(auth)/auth/confirm'
import { Route as pagesuserSettingsRouteRouteImport } from './routes/(pages)/(user)/settings/route'
import { Route as pagesuserSettingsIndexRouteImport } from './routes/(pages)/(user)/settings/index'
import { Route as ApiAssetAssetIdMetadataRouteImport } from './routes/api/asset/$assetId.metadata'
import { Route as pagesuserSettingsProfileRouteImport } from './routes/(pages)/(user)/settings/profile'

const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesRouteRoute = pagesRouteRouteImport.update({
  id: '/(pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const pagesuserRouteRoute = pagesuserRouteRouteImport.update({
  id: '/(user)',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagessearchIndexRoute = pagessearchIndexRouteImport.update({
  id: '/(search)/',
  path: '/',
  getParentRoute: () => pagesRouteRoute,
} as any)
const ApiAssetAssetIdRoute = ApiAssetAssetIdRouteImport.update({
  id: '/api/asset/$assetId',
  path: '/api/asset/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlbumsAlbumIdRoute = ApiAlbumsAlbumIdRouteImport.update({
  id: '/api/albums/$albumId',
  path: '/api/albums/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesProfileProfileIdRoute = pagesProfileProfileIdRouteImport.update({
  id: '/profile/$profileId',
  path: '/profile/$profileId',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesAssetsAssetIdRoute = pagesAssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesAlbumsAlbumIdRoute = pagesAlbumsAlbumIdRouteImport.update({
  id: '/albums/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesuserFavoritesRoute = pagesuserFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => pagesuserRouteRoute,
} as any)
const authAuthUpdatePasswordRoute = authAuthUpdatePasswordRouteImport.update({
  id: '/auth/update-password',
  path: '/auth/update-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authAuthForgotPasswordRoute = authAuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authAuthConfirmErrorRoute = authAuthConfirmErrorRouteImport.update({
  id: '/auth/confirm-error',
  path: '/auth/confirm-error',
  getParentRoute: () => authRouteRoute,
} as any)
const authAuthConfirmRoute = authAuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => authRouteRoute,
} as any)
const pagesuserSettingsRouteRoute = pagesuserSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => pagesuserRouteRoute,
} as any)
const pagesuserSettingsIndexRoute = pagesuserSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => pagesuserSettingsRouteRoute,
} as any)
const ApiAssetAssetIdMetadataRoute = ApiAssetAssetIdMetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => ApiAssetAssetIdRoute,
} as any)
const pagesuserSettingsProfileRoute =
  pagesuserSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => pagesuserSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/api/search': typeof ApiSearchRoute
  '/collections/': typeof CollectionsIndexRoute
  '/settings': typeof pagesuserSettingsRouteRouteWithChildren
  '/auth/confirm': typeof authAuthConfirmRoute
  '/auth/confirm-error': typeof authAuthConfirmErrorRoute
  '/auth/forgot-password': typeof authAuthForgotPasswordRoute
  '/auth/update-password': typeof authAuthUpdatePasswordRoute
  '/favorites': typeof pagesuserFavoritesRoute
  '/albums/$albumId': typeof pagesAlbumsAlbumIdRoute
  '/assets/$assetId': typeof pagesAssetsAssetIdRoute
  '/profile/$profileId': typeof pagesProfileProfileIdRoute
  '/api/albums/$albumId': typeof ApiAlbumsAlbumIdRoute
  '/api/asset/$assetId': typeof ApiAssetAssetIdRouteWithChildren
  '/': typeof pagessearchIndexRoute
  '/settings/profile': typeof pagesuserSettingsProfileRoute
  '/api/asset/$assetId/metadata': typeof ApiAssetAssetIdMetadataRoute
  '/settings/': typeof pagesuserSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/api/search': typeof ApiSearchRoute
  '/collections': typeof CollectionsIndexRoute
  '/auth/confirm': typeof authAuthConfirmRoute
  '/auth/confirm-error': typeof authAuthConfirmErrorRoute
  '/auth/forgot-password': typeof authAuthForgotPasswordRoute
  '/auth/update-password': typeof authAuthUpdatePasswordRoute
  '/favorites': typeof pagesuserFavoritesRoute
  '/albums/$albumId': typeof pagesAlbumsAlbumIdRoute
  '/assets/$assetId': typeof pagesAssetsAssetIdRoute
  '/profile/$profileId': typeof pagesProfileProfileIdRoute
  '/api/albums/$albumId': typeof ApiAlbumsAlbumIdRoute
  '/api/asset/$assetId': typeof ApiAssetAssetIdRouteWithChildren
  '/': typeof pagessearchIndexRoute
  '/settings/profile': typeof pagesuserSettingsProfileRoute
  '/api/asset/$assetId/metadata': typeof ApiAssetAssetIdMetadataRoute
  '/settings': typeof pagesuserSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(pages)': typeof pagesRouteRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/(pages)/(user)': typeof pagesuserRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/api/search': typeof ApiSearchRoute
  '/collections/': typeof CollectionsIndexRoute
  '/(pages)/(user)/settings': typeof pagesuserSettingsRouteRouteWithChildren
  '/(auth)/auth/confirm': typeof authAuthConfirmRoute
  '/(auth)/auth/confirm-error': typeof authAuthConfirmErrorRoute
  '/(auth)/auth/forgot-password': typeof authAuthForgotPasswordRoute
  '/(auth)/auth/update-password': typeof authAuthUpdatePasswordRoute
  '/(pages)/(user)/favorites': typeof pagesuserFavoritesRoute
  '/(pages)/albums/$albumId': typeof pagesAlbumsAlbumIdRoute
  '/(pages)/assets/$assetId': typeof pagesAssetsAssetIdRoute
  '/(pages)/profile/$profileId': typeof pagesProfileProfileIdRoute
  '/api/albums/$albumId': typeof ApiAlbumsAlbumIdRoute
  '/api/asset/$assetId': typeof ApiAssetAssetIdRouteWithChildren
  '/(pages)/(search)/': typeof pagessearchIndexRoute
  '/(pages)/(user)/settings/profile': typeof pagesuserSettingsProfileRoute
  '/api/asset/$assetId/metadata': typeof ApiAssetAssetIdMetadataRoute
  '/(pages)/(user)/settings/': typeof pagesuserSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/complete-profile'
    | '/login'
    | '/register'
    | '/api/search'
    | '/collections/'
    | '/settings'
    | '/auth/confirm'
    | '/auth/confirm-error'
    | '/auth/forgot-password'
    | '/auth/update-password'
    | '/favorites'
    | '/albums/$albumId'
    | '/assets/$assetId'
    | '/profile/$profileId'
    | '/api/albums/$albumId'
    | '/api/asset/$assetId'
    | '/'
    | '/settings/profile'
    | '/api/asset/$assetId/metadata'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/complete-profile'
    | '/login'
    | '/register'
    | '/api/search'
    | '/collections'
    | '/auth/confirm'
    | '/auth/confirm-error'
    | '/auth/forgot-password'
    | '/auth/update-password'
    | '/favorites'
    | '/albums/$albumId'
    | '/assets/$assetId'
    | '/profile/$profileId'
    | '/api/albums/$albumId'
    | '/api/asset/$assetId'
    | '/'
    | '/settings/profile'
    | '/api/asset/$assetId/metadata'
    | '/settings'
  id:
    | '__root__'
    | '/(auth)'
    | '/(pages)'
    | '/complete-profile'
    | '/(pages)/(user)'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/api/search'
    | '/collections/'
    | '/(pages)/(user)/settings'
    | '/(auth)/auth/confirm'
    | '/(auth)/auth/confirm-error'
    | '/(auth)/auth/forgot-password'
    | '/(auth)/auth/update-password'
    | '/(pages)/(user)/favorites'
    | '/(pages)/albums/$albumId'
    | '/(pages)/assets/$assetId'
    | '/(pages)/profile/$profileId'
    | '/api/albums/$albumId'
    | '/api/asset/$assetId'
    | '/(pages)/(search)/'
    | '/(pages)/(user)/settings/profile'
    | '/api/asset/$assetId/metadata'
    | '/(pages)/(user)/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  pagesRouteRoute: typeof pagesRouteRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  ApiSearchRoute: typeof ApiSearchRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ApiAlbumsAlbumIdRoute: typeof ApiAlbumsAlbumIdRoute
  ApiAssetAssetIdRoute: typeof ApiAssetAssetIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)': {
      id: '/(pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof pagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(pages)/(user)': {
      id: '/(pages)/(user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof pagesuserRouteRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/(search)/': {
      id: '/(pages)/(search)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof pagessearchIndexRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/api/asset/$assetId': {
      id: '/api/asset/$assetId'
      path: '/api/asset/$assetId'
      fullPath: '/api/asset/$assetId'
      preLoaderRoute: typeof ApiAssetAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/albums/$albumId': {
      id: '/api/albums/$albumId'
      path: '/api/albums/$albumId'
      fullPath: '/api/albums/$albumId'
      preLoaderRoute: typeof ApiAlbumsAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/profile/$profileId': {
      id: '/(pages)/profile/$profileId'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof pagesProfileProfileIdRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/assets/$assetId': {
      id: '/(pages)/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof pagesAssetsAssetIdRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/albums/$albumId': {
      id: '/(pages)/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof pagesAlbumsAlbumIdRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/(user)/favorites': {
      id: '/(pages)/(user)/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof pagesuserFavoritesRouteImport
      parentRoute: typeof pagesuserRouteRoute
    }
    '/(auth)/auth/update-password': {
      id: '/(auth)/auth/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof authAuthUpdatePasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/auth/forgot-password': {
      id: '/(auth)/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof authAuthForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/auth/confirm-error': {
      id: '/(auth)/auth/confirm-error'
      path: '/auth/confirm-error'
      fullPath: '/auth/confirm-error'
      preLoaderRoute: typeof authAuthConfirmErrorRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/auth/confirm': {
      id: '/(auth)/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof authAuthConfirmRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(pages)/(user)/settings': {
      id: '/(pages)/(user)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof pagesuserSettingsRouteRouteImport
      parentRoute: typeof pagesuserRouteRoute
    }
    '/(pages)/(user)/settings/': {
      id: '/(pages)/(user)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof pagesuserSettingsIndexRouteImport
      parentRoute: typeof pagesuserSettingsRouteRoute
    }
    '/api/asset/$assetId/metadata': {
      id: '/api/asset/$assetId/metadata'
      path: '/metadata'
      fullPath: '/api/asset/$assetId/metadata'
      preLoaderRoute: typeof ApiAssetAssetIdMetadataRouteImport
      parentRoute: typeof ApiAssetAssetIdRoute
    }
    '/(pages)/(user)/settings/profile': {
      id: '/(pages)/(user)/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof pagesuserSettingsProfileRouteImport
      parentRoute: typeof pagesuserSettingsRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authAuthConfirmRoute: typeof authAuthConfirmRoute
  authAuthConfirmErrorRoute: typeof authAuthConfirmErrorRoute
  authAuthForgotPasswordRoute: typeof authAuthForgotPasswordRoute
  authAuthUpdatePasswordRoute: typeof authAuthUpdatePasswordRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authAuthConfirmRoute: authAuthConfirmRoute,
  authAuthConfirmErrorRoute: authAuthConfirmErrorRoute,
  authAuthForgotPasswordRoute: authAuthForgotPasswordRoute,
  authAuthUpdatePasswordRoute: authAuthUpdatePasswordRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface pagesuserSettingsRouteRouteChildren {
  pagesuserSettingsProfileRoute: typeof pagesuserSettingsProfileRoute
  pagesuserSettingsIndexRoute: typeof pagesuserSettingsIndexRoute
}

const pagesuserSettingsRouteRouteChildren: pagesuserSettingsRouteRouteChildren =
  {
    pagesuserSettingsProfileRoute: pagesuserSettingsProfileRoute,
    pagesuserSettingsIndexRoute: pagesuserSettingsIndexRoute,
  }

const pagesuserSettingsRouteRouteWithChildren =
  pagesuserSettingsRouteRoute._addFileChildren(
    pagesuserSettingsRouteRouteChildren,
  )

interface pagesuserRouteRouteChildren {
  pagesuserSettingsRouteRoute: typeof pagesuserSettingsRouteRouteWithChildren
  pagesuserFavoritesRoute: typeof pagesuserFavoritesRoute
}

const pagesuserRouteRouteChildren: pagesuserRouteRouteChildren = {
  pagesuserSettingsRouteRoute: pagesuserSettingsRouteRouteWithChildren,
  pagesuserFavoritesRoute: pagesuserFavoritesRoute,
}

const pagesuserRouteRouteWithChildren = pagesuserRouteRoute._addFileChildren(
  pagesuserRouteRouteChildren,
)

interface pagesRouteRouteChildren {
  pagesuserRouteRoute: typeof pagesuserRouteRouteWithChildren
  pagesAlbumsAlbumIdRoute: typeof pagesAlbumsAlbumIdRoute
  pagesAssetsAssetIdRoute: typeof pagesAssetsAssetIdRoute
  pagesProfileProfileIdRoute: typeof pagesProfileProfileIdRoute
  pagessearchIndexRoute: typeof pagessearchIndexRoute
}

const pagesRouteRouteChildren: pagesRouteRouteChildren = {
  pagesuserRouteRoute: pagesuserRouteRouteWithChildren,
  pagesAlbumsAlbumIdRoute: pagesAlbumsAlbumIdRoute,
  pagesAssetsAssetIdRoute: pagesAssetsAssetIdRoute,
  pagesProfileProfileIdRoute: pagesProfileProfileIdRoute,
  pagessearchIndexRoute: pagessearchIndexRoute,
}

const pagesRouteRouteWithChildren = pagesRouteRoute._addFileChildren(
  pagesRouteRouteChildren,
)

interface ApiAssetAssetIdRouteChildren {
  ApiAssetAssetIdMetadataRoute: typeof ApiAssetAssetIdMetadataRoute
}

const ApiAssetAssetIdRouteChildren: ApiAssetAssetIdRouteChildren = {
  ApiAssetAssetIdMetadataRoute: ApiAssetAssetIdMetadataRoute,
}

const ApiAssetAssetIdRouteWithChildren = ApiAssetAssetIdRoute._addFileChildren(
  ApiAssetAssetIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  pagesRouteRoute: pagesRouteRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  ApiSearchRoute: ApiSearchRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ApiAlbumsAlbumIdRoute: ApiAlbumsAlbumIdRoute,
  ApiAssetAssetIdRoute: ApiAssetAssetIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
