/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as DevRouteRouteImport } from './routes/dev/route'
import { Route as pagesRouteRouteImport } from './routes/(pages)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as DevIndexRouteImport } from './routes/dev/index'
import { Route as pagesIndexRouteImport } from './routes/(pages)/index'
import { Route as pagesButtonsRouteImport } from './routes/(pages)/buttons'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as DevUiRouteRouteImport } from './routes/dev/ui/route'
import { Route as DevObservabilityRouteRouteImport } from './routes/dev/observability/route'
import { Route as pagesuserRouteRouteImport } from './routes/(pages)/(user)/route'
import { Route as DevUiIndexRouteImport } from './routes/dev/ui/index'
import { Route as DevObservabilityIndexRouteImport } from './routes/dev/observability/index'
import { Route as DevUiFeedbackRouteImport } from './routes/dev/ui/feedback'
import { Route as DevUiControlsRouteImport } from './routes/dev/ui/controls'
import { Route as DevObservabilityServerErrorRouteImport } from './routes/dev/observability/server-error'
import { Route as DevObservabilityHandled400RouteImport } from './routes/dev/observability/handled-400'
import { Route as ApiV1SearchRouteImport } from './routes/api/v1/search'
import { Route as pagesProfileProfileIdRouteImport } from './routes/(pages)/profile.$profileId'
import { Route as pagesuserFavoritesRouteImport } from './routes/(pages)/(user)/favorites'
import { Route as pagessearchSearchRouteImport } from './routes/(pages)/(search)/search'
import { Route as authAuthUpdatePasswordRouteImport } from './routes/(auth)/auth/update-password'
import { Route as authAuthForgotPasswordRouteImport } from './routes/(auth)/auth/forgot-password'
import { Route as authAuthConfirmErrorRouteImport } from './routes/(auth)/auth/confirm-error'
import { Route as authAuthConfirmRouteImport } from './routes/(auth)/auth/confirm'
import { Route as pagesuserSettingsIndexRouteImport } from './routes/(pages)/(user)/settings/index'
import { Route as pagesAssetsProviderIdAssetIdRouteImport } from './routes/(pages)/assets/$providerId.$assetId'
import { Route as pagesAlbumsProviderIdAlbumIdRouteImport } from './routes/(pages)/albums/$providerId.$albumId'
import { Route as pagesuserSettingsProfileRouteImport } from './routes/(pages)/(user)/settings/profile'
import { Route as ApiV1AssetProviderIdAssetIdRouteImport } from './routes/api/v1/asset/$providerId.$assetId'
import { Route as ApiV1AlbumsProviderIdAlbumIdRouteImport } from './routes/api/v1/albums/$providerId.$albumId'
import { Route as ApiV1AssetProviderIdAssetIdMetadataRouteImport } from './routes/api/v1/asset/$providerId.$assetId.metadata'

const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRouteRoute = DevRouteRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesRouteRoute = pagesRouteRouteImport.update({
  id: '/(pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRouteRoute,
} as any)
const pagesIndexRoute = pagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesButtonsRoute = pagesButtonsRouteImport.update({
  id: '/buttons',
  path: '/buttons',
  getParentRoute: () => pagesRouteRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const DevUiRouteRoute = DevUiRouteRouteImport.update({
  id: '/ui',
  path: '/ui',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevObservabilityRouteRoute = DevObservabilityRouteRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => DevRouteRoute,
} as any)
const pagesuserRouteRoute = pagesuserRouteRouteImport.update({
  id: '/(user)',
  getParentRoute: () => pagesRouteRoute,
} as any)
const DevUiIndexRoute = DevUiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevUiRouteRoute,
} as any)
const DevObservabilityIndexRoute = DevObservabilityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevObservabilityRouteRoute,
} as any)
const DevUiFeedbackRoute = DevUiFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => DevUiRouteRoute,
} as any)
const DevUiControlsRoute = DevUiControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => DevUiRouteRoute,
} as any)
const DevObservabilityServerErrorRoute =
  DevObservabilityServerErrorRouteImport.update({
    id: '/server-error',
    path: '/server-error',
    getParentRoute: () => DevObservabilityRouteRoute,
  } as any)
const DevObservabilityHandled400Route =
  DevObservabilityHandled400RouteImport.update({
    id: '/handled-400',
    path: '/handled-400',
    getParentRoute: () => DevObservabilityRouteRoute,
  } as any)
const ApiV1SearchRoute = ApiV1SearchRouteImport.update({
  id: '/api/v1/search',
  path: '/api/v1/search',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesProfileProfileIdRoute = pagesProfileProfileIdRouteImport.update({
  id: '/profile/$profileId',
  path: '/profile/$profileId',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesuserFavoritesRoute = pagesuserFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => pagesuserRouteRoute,
} as any)
const pagessearchSearchRoute = pagessearchSearchRouteImport.update({
  id: '/(search)/search',
  path: '/search',
  getParentRoute: () => pagesRouteRoute,
} as any)
const authAuthUpdatePasswordRoute = authAuthUpdatePasswordRouteImport.update({
  id: '/auth/update-password',
  path: '/auth/update-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authAuthForgotPasswordRoute = authAuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authAuthConfirmErrorRoute = authAuthConfirmErrorRouteImport.update({
  id: '/auth/confirm-error',
  path: '/auth/confirm-error',
  getParentRoute: () => authRouteRoute,
} as any)
const authAuthConfirmRoute = authAuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => authRouteRoute,
} as any)
const pagesuserSettingsIndexRoute = pagesuserSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => pagesuserRouteRoute,
} as any)
const pagesAssetsProviderIdAssetIdRoute =
  pagesAssetsProviderIdAssetIdRouteImport.update({
    id: '/assets/$providerId/$assetId',
    path: '/assets/$providerId/$assetId',
    getParentRoute: () => pagesRouteRoute,
  } as any)
const pagesAlbumsProviderIdAlbumIdRoute =
  pagesAlbumsProviderIdAlbumIdRouteImport.update({
    id: '/albums/$providerId/$albumId',
    path: '/albums/$providerId/$albumId',
    getParentRoute: () => pagesRouteRoute,
  } as any)
const pagesuserSettingsProfileRoute =
  pagesuserSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => pagesuserRouteRoute,
  } as any)
const ApiV1AssetProviderIdAssetIdRoute =
  ApiV1AssetProviderIdAssetIdRouteImport.update({
    id: '/api/v1/asset/$providerId/$assetId',
    path: '/api/v1/asset/$providerId/$assetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AlbumsProviderIdAlbumIdRoute =
  ApiV1AlbumsProviderIdAlbumIdRouteImport.update({
    id: '/api/v1/albums/$providerId/$albumId',
    path: '/api/v1/albums/$providerId/$albumId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1AssetProviderIdAssetIdMetadataRoute =
  ApiV1AssetProviderIdAssetIdMetadataRouteImport.update({
    id: '/metadata',
    path: '/metadata',
    getParentRoute: () => ApiV1AssetProviderIdAssetIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dev': typeof DevRouteRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/dev/observability': typeof DevObservabilityRouteRouteWithChildren
  '/dev/ui': typeof DevUiRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/buttons': typeof pagesButtonsRoute
  '/': typeof pagesIndexRoute
  '/dev/': typeof DevIndexRoute
  '/auth/confirm': typeof authAuthConfirmRoute
  '/auth/confirm-error': typeof authAuthConfirmErrorRoute
  '/auth/forgot-password': typeof authAuthForgotPasswordRoute
  '/auth/update-password': typeof authAuthUpdatePasswordRoute
  '/search': typeof pagessearchSearchRoute
  '/favorites': typeof pagesuserFavoritesRoute
  '/profile/$profileId': typeof pagesProfileProfileIdRoute
  '/api/v1/search': typeof ApiV1SearchRoute
  '/dev/observability/handled-400': typeof DevObservabilityHandled400Route
  '/dev/observability/server-error': typeof DevObservabilityServerErrorRoute
  '/dev/ui/controls': typeof DevUiControlsRoute
  '/dev/ui/feedback': typeof DevUiFeedbackRoute
  '/dev/observability/': typeof DevObservabilityIndexRoute
  '/dev/ui/': typeof DevUiIndexRoute
  '/settings/profile': typeof pagesuserSettingsProfileRoute
  '/albums/$providerId/$albumId': typeof pagesAlbumsProviderIdAlbumIdRoute
  '/assets/$providerId/$assetId': typeof pagesAssetsProviderIdAssetIdRoute
  '/settings/': typeof pagesuserSettingsIndexRoute
  '/api/v1/albums/$providerId/$albumId': typeof ApiV1AlbumsProviderIdAlbumIdRoute
  '/api/v1/asset/$providerId/$assetId': typeof ApiV1AssetProviderIdAssetIdRouteWithChildren
  '/api/v1/asset/$providerId/$assetId/metadata': typeof ApiV1AssetProviderIdAssetIdMetadataRoute
}
export interface FileRoutesByTo {
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/buttons': typeof pagesButtonsRoute
  '/': typeof pagesIndexRoute
  '/dev': typeof DevIndexRoute
  '/auth/confirm': typeof authAuthConfirmRoute
  '/auth/confirm-error': typeof authAuthConfirmErrorRoute
  '/auth/forgot-password': typeof authAuthForgotPasswordRoute
  '/auth/update-password': typeof authAuthUpdatePasswordRoute
  '/search': typeof pagessearchSearchRoute
  '/favorites': typeof pagesuserFavoritesRoute
  '/profile/$profileId': typeof pagesProfileProfileIdRoute
  '/api/v1/search': typeof ApiV1SearchRoute
  '/dev/observability/handled-400': typeof DevObservabilityHandled400Route
  '/dev/observability/server-error': typeof DevObservabilityServerErrorRoute
  '/dev/ui/controls': typeof DevUiControlsRoute
  '/dev/ui/feedback': typeof DevUiFeedbackRoute
  '/dev/observability': typeof DevObservabilityIndexRoute
  '/dev/ui': typeof DevUiIndexRoute
  '/settings/profile': typeof pagesuserSettingsProfileRoute
  '/albums/$providerId/$albumId': typeof pagesAlbumsProviderIdAlbumIdRoute
  '/assets/$providerId/$assetId': typeof pagesAssetsProviderIdAssetIdRoute
  '/settings': typeof pagesuserSettingsIndexRoute
  '/api/v1/albums/$providerId/$albumId': typeof ApiV1AlbumsProviderIdAlbumIdRoute
  '/api/v1/asset/$providerId/$assetId': typeof ApiV1AssetProviderIdAssetIdRouteWithChildren
  '/api/v1/asset/$providerId/$assetId/metadata': typeof ApiV1AssetProviderIdAssetIdMetadataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(pages)': typeof pagesRouteRouteWithChildren
  '/dev': typeof DevRouteRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/(pages)/(user)': typeof pagesuserRouteRouteWithChildren
  '/dev/observability': typeof DevObservabilityRouteRouteWithChildren
  '/dev/ui': typeof DevUiRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(pages)/buttons': typeof pagesButtonsRoute
  '/(pages)/': typeof pagesIndexRoute
  '/dev/': typeof DevIndexRoute
  '/(auth)/auth/confirm': typeof authAuthConfirmRoute
  '/(auth)/auth/confirm-error': typeof authAuthConfirmErrorRoute
  '/(auth)/auth/forgot-password': typeof authAuthForgotPasswordRoute
  '/(auth)/auth/update-password': typeof authAuthUpdatePasswordRoute
  '/(pages)/(search)/search': typeof pagessearchSearchRoute
  '/(pages)/(user)/favorites': typeof pagesuserFavoritesRoute
  '/(pages)/profile/$profileId': typeof pagesProfileProfileIdRoute
  '/api/v1/search': typeof ApiV1SearchRoute
  '/dev/observability/handled-400': typeof DevObservabilityHandled400Route
  '/dev/observability/server-error': typeof DevObservabilityServerErrorRoute
  '/dev/ui/controls': typeof DevUiControlsRoute
  '/dev/ui/feedback': typeof DevUiFeedbackRoute
  '/dev/observability/': typeof DevObservabilityIndexRoute
  '/dev/ui/': typeof DevUiIndexRoute
  '/(pages)/(user)/settings/profile': typeof pagesuserSettingsProfileRoute
  '/(pages)/albums/$providerId/$albumId': typeof pagesAlbumsProviderIdAlbumIdRoute
  '/(pages)/assets/$providerId/$assetId': typeof pagesAssetsProviderIdAssetIdRoute
  '/(pages)/(user)/settings/': typeof pagesuserSettingsIndexRoute
  '/api/v1/albums/$providerId/$albumId': typeof ApiV1AlbumsProviderIdAlbumIdRoute
  '/api/v1/asset/$providerId/$assetId': typeof ApiV1AssetProviderIdAssetIdRouteWithChildren
  '/api/v1/asset/$providerId/$assetId/metadata': typeof ApiV1AssetProviderIdAssetIdMetadataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dev'
    | '/complete-profile'
    | '/dev/observability'
    | '/dev/ui'
    | '/login'
    | '/register'
    | '/buttons'
    | '/'
    | '/dev/'
    | '/auth/confirm'
    | '/auth/confirm-error'
    | '/auth/forgot-password'
    | '/auth/update-password'
    | '/search'
    | '/favorites'
    | '/profile/$profileId'
    | '/api/v1/search'
    | '/dev/observability/handled-400'
    | '/dev/observability/server-error'
    | '/dev/ui/controls'
    | '/dev/ui/feedback'
    | '/dev/observability/'
    | '/dev/ui/'
    | '/settings/profile'
    | '/albums/$providerId/$albumId'
    | '/assets/$providerId/$assetId'
    | '/settings/'
    | '/api/v1/albums/$providerId/$albumId'
    | '/api/v1/asset/$providerId/$assetId'
    | '/api/v1/asset/$providerId/$assetId/metadata'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/complete-profile'
    | '/login'
    | '/register'
    | '/buttons'
    | '/'
    | '/dev'
    | '/auth/confirm'
    | '/auth/confirm-error'
    | '/auth/forgot-password'
    | '/auth/update-password'
    | '/search'
    | '/favorites'
    | '/profile/$profileId'
    | '/api/v1/search'
    | '/dev/observability/handled-400'
    | '/dev/observability/server-error'
    | '/dev/ui/controls'
    | '/dev/ui/feedback'
    | '/dev/observability'
    | '/dev/ui'
    | '/settings/profile'
    | '/albums/$providerId/$albumId'
    | '/assets/$providerId/$assetId'
    | '/settings'
    | '/api/v1/albums/$providerId/$albumId'
    | '/api/v1/asset/$providerId/$assetId'
    | '/api/v1/asset/$providerId/$assetId/metadata'
  id:
    | '__root__'
    | '/(auth)'
    | '/(pages)'
    | '/dev'
    | '/complete-profile'
    | '/(pages)/(user)'
    | '/dev/observability'
    | '/dev/ui'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(pages)/buttons'
    | '/(pages)/'
    | '/dev/'
    | '/(auth)/auth/confirm'
    | '/(auth)/auth/confirm-error'
    | '/(auth)/auth/forgot-password'
    | '/(auth)/auth/update-password'
    | '/(pages)/(search)/search'
    | '/(pages)/(user)/favorites'
    | '/(pages)/profile/$profileId'
    | '/api/v1/search'
    | '/dev/observability/handled-400'
    | '/dev/observability/server-error'
    | '/dev/ui/controls'
    | '/dev/ui/feedback'
    | '/dev/observability/'
    | '/dev/ui/'
    | '/(pages)/(user)/settings/profile'
    | '/(pages)/albums/$providerId/$albumId'
    | '/(pages)/assets/$providerId/$assetId'
    | '/(pages)/(user)/settings/'
    | '/api/v1/albums/$providerId/$albumId'
    | '/api/v1/asset/$providerId/$assetId'
    | '/api/v1/asset/$providerId/$assetId/metadata'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  pagesRouteRoute: typeof pagesRouteRouteWithChildren
  DevRouteRoute: typeof DevRouteRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  ApiV1SearchRoute: typeof ApiV1SearchRoute
  ApiV1AlbumsProviderIdAlbumIdRoute: typeof ApiV1AlbumsProviderIdAlbumIdRoute
  ApiV1AssetProviderIdAssetIdRoute: typeof ApiV1AssetProviderIdAssetIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)': {
      id: '/(pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof pagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/(pages)/': {
      id: '/(pages)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof pagesIndexRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/buttons': {
      id: '/(pages)/buttons'
      path: '/buttons'
      fullPath: '/buttons'
      preLoaderRoute: typeof pagesButtonsRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/observability': {
      id: '/dev/observability'
      path: '/observability'
      fullPath: '/dev/observability'
      preLoaderRoute: typeof DevObservabilityRouteRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/(pages)/(user)': {
      id: '/(pages)/(user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof pagesuserRouteRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/dev/ui/': {
      id: '/dev/ui/'
      path: '/'
      fullPath: '/dev/ui/'
      preLoaderRoute: typeof DevUiIndexRouteImport
      parentRoute: typeof DevUiRouteRoute
    }
    '/dev/observability/': {
      id: '/dev/observability/'
      path: '/'
      fullPath: '/dev/observability/'
      preLoaderRoute: typeof DevObservabilityIndexRouteImport
      parentRoute: typeof DevObservabilityRouteRoute
    }
    '/dev/ui/feedback': {
      id: '/dev/ui/feedback'
      path: '/feedback'
      fullPath: '/dev/ui/feedback'
      preLoaderRoute: typeof DevUiFeedbackRouteImport
      parentRoute: typeof DevUiRouteRoute
    }
    '/dev/ui/controls': {
      id: '/dev/ui/controls'
      path: '/controls'
      fullPath: '/dev/ui/controls'
      preLoaderRoute: typeof DevUiControlsRouteImport
      parentRoute: typeof DevUiRouteRoute
    }
    '/dev/observability/server-error': {
      id: '/dev/observability/server-error'
      path: '/server-error'
      fullPath: '/dev/observability/server-error'
      preLoaderRoute: typeof DevObservabilityServerErrorRouteImport
      parentRoute: typeof DevObservabilityRouteRoute
    }
    '/dev/observability/handled-400': {
      id: '/dev/observability/handled-400'
      path: '/handled-400'
      fullPath: '/dev/observability/handled-400'
      preLoaderRoute: typeof DevObservabilityHandled400RouteImport
      parentRoute: typeof DevObservabilityRouteRoute
    }
    '/api/v1/search': {
      id: '/api/v1/search'
      path: '/api/v1/search'
      fullPath: '/api/v1/search'
      preLoaderRoute: typeof ApiV1SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)/profile/$profileId': {
      id: '/(pages)/profile/$profileId'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof pagesProfileProfileIdRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/(user)/favorites': {
      id: '/(pages)/(user)/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof pagesuserFavoritesRouteImport
      parentRoute: typeof pagesuserRouteRoute
    }
    '/(pages)/(search)/search': {
      id: '/(pages)/(search)/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof pagessearchSearchRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(auth)/auth/update-password': {
      id: '/(auth)/auth/update-password'
      path: '/auth/update-password'
      fullPath: '/auth/update-password'
      preLoaderRoute: typeof authAuthUpdatePasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/auth/forgot-password': {
      id: '/(auth)/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof authAuthForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/auth/confirm-error': {
      id: '/(auth)/auth/confirm-error'
      path: '/auth/confirm-error'
      fullPath: '/auth/confirm-error'
      preLoaderRoute: typeof authAuthConfirmErrorRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/auth/confirm': {
      id: '/(auth)/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof authAuthConfirmRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(pages)/(user)/settings/': {
      id: '/(pages)/(user)/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof pagesuserSettingsIndexRouteImport
      parentRoute: typeof pagesuserRouteRoute
    }
    '/(pages)/assets/$providerId/$assetId': {
      id: '/(pages)/assets/$providerId/$assetId'
      path: '/assets/$providerId/$assetId'
      fullPath: '/assets/$providerId/$assetId'
      preLoaderRoute: typeof pagesAssetsProviderIdAssetIdRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/albums/$providerId/$albumId': {
      id: '/(pages)/albums/$providerId/$albumId'
      path: '/albums/$providerId/$albumId'
      fullPath: '/albums/$providerId/$albumId'
      preLoaderRoute: typeof pagesAlbumsProviderIdAlbumIdRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/(user)/settings/profile': {
      id: '/(pages)/(user)/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof pagesuserSettingsProfileRouteImport
      parentRoute: typeof pagesuserRouteRoute
    }
    '/api/v1/asset/$providerId/$assetId': {
      id: '/api/v1/asset/$providerId/$assetId'
      path: '/api/v1/asset/$providerId/$assetId'
      fullPath: '/api/v1/asset/$providerId/$assetId'
      preLoaderRoute: typeof ApiV1AssetProviderIdAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/albums/$providerId/$albumId': {
      id: '/api/v1/albums/$providerId/$albumId'
      path: '/api/v1/albums/$providerId/$albumId'
      fullPath: '/api/v1/albums/$providerId/$albumId'
      preLoaderRoute: typeof ApiV1AlbumsProviderIdAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/asset/$providerId/$assetId/metadata': {
      id: '/api/v1/asset/$providerId/$assetId/metadata'
      path: '/metadata'
      fullPath: '/api/v1/asset/$providerId/$assetId/metadata'
      preLoaderRoute: typeof ApiV1AssetProviderIdAssetIdMetadataRouteImport
      parentRoute: typeof ApiV1AssetProviderIdAssetIdRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authAuthConfirmRoute: typeof authAuthConfirmRoute
  authAuthConfirmErrorRoute: typeof authAuthConfirmErrorRoute
  authAuthForgotPasswordRoute: typeof authAuthForgotPasswordRoute
  authAuthUpdatePasswordRoute: typeof authAuthUpdatePasswordRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authAuthConfirmRoute: authAuthConfirmRoute,
  authAuthConfirmErrorRoute: authAuthConfirmErrorRoute,
  authAuthForgotPasswordRoute: authAuthForgotPasswordRoute,
  authAuthUpdatePasswordRoute: authAuthUpdatePasswordRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface pagesuserRouteRouteChildren {
  pagesuserFavoritesRoute: typeof pagesuserFavoritesRoute
  pagesuserSettingsProfileRoute: typeof pagesuserSettingsProfileRoute
  pagesuserSettingsIndexRoute: typeof pagesuserSettingsIndexRoute
}

const pagesuserRouteRouteChildren: pagesuserRouteRouteChildren = {
  pagesuserFavoritesRoute: pagesuserFavoritesRoute,
  pagesuserSettingsProfileRoute: pagesuserSettingsProfileRoute,
  pagesuserSettingsIndexRoute: pagesuserSettingsIndexRoute,
}

const pagesuserRouteRouteWithChildren = pagesuserRouteRoute._addFileChildren(
  pagesuserRouteRouteChildren,
)

interface pagesRouteRouteChildren {
  pagesuserRouteRoute: typeof pagesuserRouteRouteWithChildren
  pagesButtonsRoute: typeof pagesButtonsRoute
  pagesIndexRoute: typeof pagesIndexRoute
  pagessearchSearchRoute: typeof pagessearchSearchRoute
  pagesProfileProfileIdRoute: typeof pagesProfileProfileIdRoute
  pagesAlbumsProviderIdAlbumIdRoute: typeof pagesAlbumsProviderIdAlbumIdRoute
  pagesAssetsProviderIdAssetIdRoute: typeof pagesAssetsProviderIdAssetIdRoute
}

const pagesRouteRouteChildren: pagesRouteRouteChildren = {
  pagesuserRouteRoute: pagesuserRouteRouteWithChildren,
  pagesButtonsRoute: pagesButtonsRoute,
  pagesIndexRoute: pagesIndexRoute,
  pagessearchSearchRoute: pagessearchSearchRoute,
  pagesProfileProfileIdRoute: pagesProfileProfileIdRoute,
  pagesAlbumsProviderIdAlbumIdRoute: pagesAlbumsProviderIdAlbumIdRoute,
  pagesAssetsProviderIdAssetIdRoute: pagesAssetsProviderIdAssetIdRoute,
}

const pagesRouteRouteWithChildren = pagesRouteRoute._addFileChildren(
  pagesRouteRouteChildren,
)

interface DevObservabilityRouteRouteChildren {
  DevObservabilityHandled400Route: typeof DevObservabilityHandled400Route
  DevObservabilityServerErrorRoute: typeof DevObservabilityServerErrorRoute
  DevObservabilityIndexRoute: typeof DevObservabilityIndexRoute
}

const DevObservabilityRouteRouteChildren: DevObservabilityRouteRouteChildren = {
  DevObservabilityHandled400Route: DevObservabilityHandled400Route,
  DevObservabilityServerErrorRoute: DevObservabilityServerErrorRoute,
  DevObservabilityIndexRoute: DevObservabilityIndexRoute,
}

const DevObservabilityRouteRouteWithChildren =
  DevObservabilityRouteRoute._addFileChildren(
    DevObservabilityRouteRouteChildren,
  )

interface DevUiRouteRouteChildren {
  DevUiControlsRoute: typeof DevUiControlsRoute
  DevUiFeedbackRoute: typeof DevUiFeedbackRoute
  DevUiIndexRoute: typeof DevUiIndexRoute
}

const DevUiRouteRouteChildren: DevUiRouteRouteChildren = {
  DevUiControlsRoute: DevUiControlsRoute,
  DevUiFeedbackRoute: DevUiFeedbackRoute,
  DevUiIndexRoute: DevUiIndexRoute,
}

const DevUiRouteRouteWithChildren = DevUiRouteRoute._addFileChildren(
  DevUiRouteRouteChildren,
)

interface DevRouteRouteChildren {
  DevObservabilityRouteRoute: typeof DevObservabilityRouteRouteWithChildren
  DevUiRouteRoute: typeof DevUiRouteRouteWithChildren
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteRouteChildren: DevRouteRouteChildren = {
  DevObservabilityRouteRoute: DevObservabilityRouteRouteWithChildren,
  DevUiRouteRoute: DevUiRouteRouteWithChildren,
  DevIndexRoute: DevIndexRoute,
}

const DevRouteRouteWithChildren = DevRouteRoute._addFileChildren(
  DevRouteRouteChildren,
)

interface ApiV1AssetProviderIdAssetIdRouteChildren {
  ApiV1AssetProviderIdAssetIdMetadataRoute: typeof ApiV1AssetProviderIdAssetIdMetadataRoute
}

const ApiV1AssetProviderIdAssetIdRouteChildren: ApiV1AssetProviderIdAssetIdRouteChildren =
  {
    ApiV1AssetProviderIdAssetIdMetadataRoute:
      ApiV1AssetProviderIdAssetIdMetadataRoute,
  }

const ApiV1AssetProviderIdAssetIdRouteWithChildren =
  ApiV1AssetProviderIdAssetIdRoute._addFileChildren(
    ApiV1AssetProviderIdAssetIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  pagesRouteRoute: pagesRouteRouteWithChildren,
  DevRouteRoute: DevRouteRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  ApiV1SearchRoute: ApiV1SearchRoute,
  ApiV1AlbumsProviderIdAlbumIdRoute: ApiV1AlbumsProviderIdAlbumIdRoute,
  ApiV1AssetProviderIdAssetIdRoute:
    ApiV1AssetProviderIdAssetIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
