/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiAssetAssetIdRouteImport } from './routes/api/asset/$assetId'
import { Route as ApiAlbumsAlbumIdRouteImport } from './routes/api/albums/$albumId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetAssetIdRoute = ApiAssetAssetIdRouteImport.update({
  id: '/api/asset/$assetId',
  path: '/api/asset/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlbumsAlbumIdRoute = ApiAlbumsAlbumIdRouteImport.update({
  id: '/api/albums/$albumId',
  path: '/api/albums/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRoute
  '/collections': typeof CollectionsIndexRoute
  '/api/albums/$albumId': typeof ApiAlbumsAlbumIdRoute
  '/api/asset/$assetId': typeof ApiAssetAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRoute
  '/collections': typeof CollectionsIndexRoute
  '/api/albums/$albumId': typeof ApiAlbumsAlbumIdRoute
  '/api/asset/$assetId': typeof ApiAssetAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRoute
  '/collections/': typeof CollectionsIndexRoute
  '/api/albums/$albumId': typeof ApiAlbumsAlbumIdRoute
  '/api/asset/$assetId': typeof ApiAssetAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/search'
    | '/collections'
    | '/api/albums/$albumId'
    | '/api/asset/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/search'
    | '/collections'
    | '/api/albums/$albumId'
    | '/api/asset/$assetId'
  id:
    | '__root__'
    | '/'
    | '/api/search'
    | '/collections/'
    | '/api/albums/$albumId'
    | '/api/asset/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSearchRoute: typeof ApiSearchRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ApiAlbumsAlbumIdRoute: typeof ApiAlbumsAlbumIdRoute
  ApiAssetAssetIdRoute: typeof ApiAssetAssetIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/asset/$assetId': {
      id: '/api/asset/$assetId'
      path: '/api/asset/$assetId'
      fullPath: '/api/asset/$assetId'
      preLoaderRoute: typeof ApiAssetAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/albums/$albumId': {
      id: '/api/albums/$albumId'
      path: '/api/albums/$albumId'
      fullPath: '/api/albums/$albumId'
      preLoaderRoute: typeof ApiAlbumsAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSearchRoute: ApiSearchRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ApiAlbumsAlbumIdRoute: ApiAlbumsAlbumIdRoute,
  ApiAssetAssetIdRoute: ApiAssetAssetIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
